"""Adding tag column to Page

Revision ID: 3fadba4c22e7
Revises: 6ba55eaec1ae
Create Date: 2018-12-03 02:23:08.891089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fadba4c22e7'
down_revision = '6ba55eaec1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'tag')
    # ### end Alembic commands ###
